In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr=np.ones([3,4])
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr=np.zeros([3,5])
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
a=np.full(4,9)
a

array([9, 9, 9, 9])

In [ ]:
a=np.arange(1,31)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
a=np.arange(2,20,2)
print(a)

[ 2  4  6  8 10 12 14 16 18]


In [ ]:
a=np.arange(1,13)
new_a=a.reshape(3,4)
print("Array:",new_a)
print("Arr shape",new_a.shape)
print("Arr dimension",new_a.ndim)
print("Arr size",new_a.size)

Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Arr shape (3, 4)
Arr dimension 2
Arr size 12


In [ ]:
a=np.array([
    [[1,2],[3,4]],
    [[5,6],[6,7]]]
    )
print(a)
print("Arr shape",a.shape)
print("Arr dimension",a.ndim)
print("Arr size",a.size)


[[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]]
Arr shape (2, 2, 2)
Arr dimension 3
Arr size 8


**Indexing**

In [ ]:
print(new_a[0][0])
print(new_a[2,3])
print(a[1][1][1])
print(a[1,0,1])

1
12
7
6


**Slicing**

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
arr

array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
arr[1:6]

array([20, 30, 40, 50, 60])

In [ ]:
arr[-3:]

array([60, 70, 80])

In [ ]:
arr[::2]

array([10, 30, 50, 70])

In [ ]:
arr[::-1]

array([80, 70, 60, 50, 40, 30, 20, 10])

In [ ]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
arr[0:1,2:3]

array([[3]])

In [ ]:
arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

arr[:2,1:2,0:1]

array([[[ 4]],

       [[10]]])

In [ ]:
arr[1,:,:]

array([[ 7,  8,  9],
       [10, 11, 12]])

**Broadcasting**

In [ ]:
a=np.array([10,20,30,40,50,60,70])
a.shape
b=10
a+b

array([20, 30, 40, 50, 60, 70, 80])

In [ ]:
a*b

array([100, 200, 300, 400])

In [ ]:
b=[10,20,30,40]
a+b

array([20, 40, 60, 80])

In [ ]:
a-b

array([0, 0, 0, 0])

**Vectorization**

In [ ]:
res=a*2
res

array([20, 40, 60, 80])

In [ ]:
a**2

array([ 100,  400,  900, 1600])

In [ ]:
a[a>30]

array([40])

In [ ]:
a[(a>=20) & (a<=40)]

array([20, 30, 40])

In [ ]:
a[a>20]=0
a

array([10, 20,  0,  0,  0,  0,  0])

**Matrix OPerations**

In [ ]:
a=np.array([
    [1,2],
    [3,4]
])
b=np.array([
    [5,6],
    [7,8]
])

In [ ]:
a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a-b

array([[-4, -4],
       [-4, -4]])

In [ ]:
print(a*b)
print(a@b)   #matrix multiplication

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [ ]:
a.T

array([[1, 3],
       [2, 4]])

In [ ]:
np.sum(a,axis=0)

array([4, 6])

In [ ]:
np.sum(a,axis=1)

array([3, 7])

**Numerical Problems**

In [ ]:
marks = np.array([78, 85, 92, 67, 88, 95, 72, 81])

In [ ]:
print(np.sum(marks))

658


In [ ]:
print(np.average(marks))

82.25


In [ ]:
print(np.max(marks))

95
